spring:
  datasource:
    url: jdbc:h2:mem:fxdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  cache:
    type: caffeine  # Using Caffeine for caching
    cache-names: exchangeRates

fixer:
  url: https://api.apilayer.com/fixer/latest
  key: u3H2ddGvuoV7nZFtgIFQV7bBiWHXT4ZG

jwt:
  secret: mysupersecretkeythatshouldbekeptsecure123456

fx:
  security:
    enabled: false

logging:
  file:
    name: logs/fx-service.log  # Relative to project root
  level:
    root: INFO
    com.example.fx: DEBUG      # Optional: more verbose for your package
